version: "3.3"

services:
  redux-post:
    container_name: redux-post
    build: ./
    volumes:
      - ".:/app"
      - "/app/node_modules"
    expose:
      - ${PORT}
    environment:
         VIRTUAL_HOST: ${URL_FRONTEND}
    networks:
      - nginx_main
      - backend

networks:
  nginx_main:
    external: true
  backend:
    external: true
